version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./source/html:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: mysql:latest  # Official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: dzw7$1 
      MYSQL_DATABASE: db 
      MYSQL_USER: jimmy 
      MYSQL_PASSWORD: dzu7$2 

  env:
    build: .
    environment:
      - PYTHON=python3
    volumes:
      - ./source:/app/source
    tty: true
    depends_on:
      - db
      - web

networks:
  default:
    driver: bridge

  